# Generated by Django 4.2.4 on 2023-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("date", models.DateField(auto_now=True)),
                ("desctiption", models.TextField()),
            ],
        ),
    ]
