# Generated by Django 4.0.5 on 2023-10-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisiterForum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('birth_date', models.DateField(null=True)),
                ('is_report', models.BooleanField()),
                ('report_theme', models.TextField(null=True)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
